const app = document.querySelector('#app');

const services = [
  { number: '01', title: 'The Small Run', copy: 'A reliable local run for the things that keep your day moving.', tone: 'yellow' },
  { number: '02', title: 'The Good Box', copy: 'Thoughtful, temperature-aware delivery for food, flowers, and care.', tone: 'blue' },
  { number: '03', title: 'The Big Move', copy: 'Extra hands and a bigger vehicle for the jobs that need a little more.', tone: 'sage' },
];

function layout(content) { app.innerHTML = `<div class="page">${content}</div>`; window.scrollTo(0, 0); }
function button(label, href = '#/request', cls = '') { return `<a class="button ${cls}" href="${href}">${label} <span>↗</span></a>`; }
function home() {
  layout(`<section class="hero"><div class="hero-copy"><p class="eyebrow">Independent delivery · built with care</p><h1 class="display">Good things<br>are <em>going places.</em></h1><p class="lede">Maloura is the thoughtful way to move what matters. Local delivery for people, small businesses, and the ideas that are just getting started.</p><div class="hero-actions">${button('Request a delivery')} ${button('Explore services', '#/services', 'secondary')}</div></div><div class="hero-art" aria-label="Illustration of a delivery route"><span class="orb one"></span><span class="orb two"></span><span class="orb three"></span><div class="delivery-card"><span class="eyebrow">On its way</span><h3>One good thing,<br>coming right up.</h3><div class="route"><span>Maloura studio</span><span>East market</span><span>Someone's table</span></div><div class="card-meta"><span>ETA 14 min</span><span>ML · 204</span></div></div></div></section><section><div class="section-heading"><h2>Choose your kind of good.</h2><p>Clear pricing, kind people, and a delivery that feels like it was made for you.</p></div><div class="service-grid">${services.map((s) => `<a class="service" href="#/request"><span class="service-num">${s.number}</span><div><h3>${s.title}</h3><p>${s.copy}</p></div><span class="service-arrow">↘</span></a>`).join('')}</div></section><section class="split-band"><div class="manifesto"><p class="eyebrow">The Maloura way</p><h2>From first idea to front door.</h2><p>Every delivery is part of a bigger picture. We help local makers move with confidence, then use what we learn to make the next thing better.</p></div><div class="flow"><h3>A living loop, not a dead end.</h3>${['Idea → Research', 'Research → Project', 'Project → Service', 'Service → Someone happy'].map((x, i) => `<div class="flow-line"><span>0${i + 1}</span><p>${x}<small>${['Find the signal.', 'Make it real.', 'Put it in motion.', 'Learn what matters.'][i]}</small></p></div>`).join('')}</div></section><div class="ticker"><span>OPEN FOR ORDERS · EASTSIDE & BEYOND</span><strong>Next pickup window · 15:30</strong></div>`);
}
function servicesPage() { layout(`<div class="dashboard-header"><div><p class="eyebrow">What we can do</p><h1>Services for<br>real life.</h1><p>Start with a clear brief. We will take care of the moving part.</p></div>${button('Start a request')}</div><div class="service-grid">${services.map((s) => `<article class="service"><span class="service-num">${s.number}</span><div><h3>${s.title}</h3><p>${s.copy}</p></div><span class="service-arrow">↘</span></article>`).join('')}</div><section class="split-band"><div><p class="eyebrow">Good to know</p><h2 class="section-heading"><span>Simple by design.</span></h2><p class="lede">We price by distance, time, and care required. No subscriptions, surge pricing, or mystery fees.</p></div><div class="panel"><h3>Every delivery includes</h3>${['A human point of contact','Live updates by text','Careful handling','A receipt for your records'].map(x => `<div class="order"><span>${x}</span><b>✓</b></div>`).join('')}</div></section>`); }
function requestPage() { layout(`<div class="form-layout"><div><p class="eyebrow">New delivery request</p><h1>Tell us what<br>needs moving.</h1><p class="lede">A few details is all we need to get you a clear estimate. Nothing is booked until you say yes.</p><form class="form" onsubmit="event.preventDefault(); saveRequest(this);"><div class="field-grid"><div class="field"><label>Pickup from</label><input name="pickup" required placeholder="Address or place name"></div><div class="field"><label>Deliver to</label><input name="dropoff" required placeholder="Address or place name"></div></div><div class="field"><label>What are we moving?</label><textarea name="description" required placeholder="A birthday cake, three boxes of books..."></textarea></div><div class="field-grid"><div class="field"><label>When</label><select name="schedule"><option>Today · ASAP</option><option>Today · 15:30</option><option>Tomorrow morning</option></select></div><div class="field"><label>Your email</label><input name="email" required type="email" placeholder="you@example.com"></div></div><button class="button" type="submit">Get my estimate ↗</button></form></div><aside class="estimate"><h3>Your estimate</h3><div class="estimate-total"><span>Starting from</span><strong>$14</strong></div><ul><li>First 3 miles included</li><li>Careful handling included</li><li>No commitment today</li></ul></aside></div>`); }
function saveRequest(form) {
  const request = Object.fromEntries(new FormData(form));
  request.id = `ML-${Date.now().toString().slice(-4)}`;
  request.createdAt = new Date().toISOString();
  const requests = JSON.parse(localStorage.getItem('maloura.delivery_requests') || '[]');
  requests.push(request);
  localStorage.setItem('maloura.delivery_requests', JSON.stringify(requests));
  form.innerHTML = `<div class="manifesto"><p class="eyebrow">Request received · ${request.id}</p><h2>We’re on it.</h2><p>We’ll review the details and email you a clear estimate shortly.</p><a class="button secondary" href="#/orders">View your orders ↗</a></div>`;
}
function ordersPage() { layout(`<div class="dashboard-header"><div><p class="eyebrow">Customer space · JD</p><h1>Your orders.</h1><p>One place for everything on the move.</p></div>${button('New request', '#/request')}</div><div class="stat-row"><div class="stat"><strong>03</strong><span>All time deliveries</span></div><div class="stat"><strong>01</strong><span>In progress</span></div><div class="stat"><strong>$186</strong><span>Total spent</span></div></div><div class="dash-grid"><section class="panel"><h3>Recent activity</h3>${[['ML-2048','Market Street → Eastside','On the way · 14 min','waiting'],['ML-2039','Studio → North Hill','Delivered yesterday',''],['ML-1982','West End → Studio','Delivered 12 Jun','']].map(x => `<div class="order"><div class="order-info"><strong>${x[0]}</strong><span>${x[1]}</span><span>${x[2]}</span></div><span class="status ${x[3]}">${x[3] ? 'IN TRANSIT' : 'DELIVERED'}</span></div>`).join('')}</section><aside class="panel"><h3>Your impact</h3><p class="lede">By choosing local, you kept</p><div class="metric"><b>11.4 kg</b><span>of CO₂ out of the air</span></div><div class="metric"><b>2.5 hrs</b><span>of time in your day</span></div><div class="metric"><b>03</b><span>local jobs moving</span></div></aside></div>`); }
function libraryPage(type) { const data = type === 'ideas' ? [['OPEN QUESTION','Can a delivery feel like a welcome?','A small business experiment for making the handoff feel as warm as the thing inside.'],['SIGNAL','People want a local default.','Early conversations point to a hunger for services that remember the neighbourhood.'],['NEXT UP','The Sunday run.','A weekly route for flowers, bread, and the other good rituals.']] : [['FIELD NOTE · 18 JUN','The last mile is personal.','Three conversations with makers about the moment their work leaves the studio.'],['REPORT · 12 JUN','Small is a serious advantage.','Patterns from our first 30 deliveries, and what they suggest for the next service.'],['READING LIST','The shape of a good service.','Five notes on care, clarity, and making something people want to return to.']]; layout(`<div class="dashboard-header"><div><p class="eyebrow">Maloura / ${type}</p><h1>${type === 'ideas' ? 'Ideas worth<br>following.' : 'A library for<br>looking closer.'}</h1><p>Notes from the work. Kept close, made useful.</p></div>${button(type === 'ideas' ? 'Add an idea' : 'Add research', '#/request', 'secondary')}</div><div class="library-grid">${data.map((x) => `<article class="library-card"><span class="tag">${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p><a href="#/projects">View the thread ↗</a></article>`).join('')}</div>`); }
function adminPage() { layout(`<div class="admin-banner"><div><h1>Maloura control center.</h1><p>Saturday, 20 June 2026 · All systems quietly humming.</p></div>${button('New project', '#/projects')}</div><div class="stat-row"><div class="stat"><strong>$4,280</strong><span>Revenue this month</span></div><div class="stat"><strong>86</strong><span>Completed orders</span></div><div class="stat"><strong>92%</strong><span>On-time rate</span></div></div><div class="dash-grid"><section class="panel"><h3>Revenue pulse</h3><div class="mini-chart">${[32,48,43,65,57,81,72,92].map(x => `<i style="height:${x}%"></i>`).join('')}</div><div class="metric"><span>June so far</span><b>+$1,204 vs May</b></div></section><aside class="panel"><h3>Today at a glance</h3><div class="metric"><b>12</b><span>open requests</span></div><div class="metric"><b>04</b><span>riders active</span></div><div class="metric"><b>02</b><span>ideas ready to test</span></div><div class="bar"><i style="width:78%"></i></div><span class="tag">WEEKLY GOAL · 78%</span></aside></div>`); }
function projectsPage() { layout(`<div class="dashboard-header"><div><p class="eyebrow">Experiments in motion</p><h1>Build, learn,<br>repeat.</h1><p>Small bets connected to the work we already do.</p></div>${button('Start a project', '#/request', 'secondary')}</div><div class="library-grid"><article class="library-card"><span class="tag">ACTIVE · 72%</span><h3>Sunday Good Run</h3><p>A recurring route that turns weekly errands into a neighbourhood ritual.</p><div class="bar"><i style="width:72%"></i></div><a href="#/admin">Open project ↗</a></article><article class="library-card"><span class="tag">RESEARCHING</span><h3>Careful Commerce</h3><p>What does it mean to deliver something fragile, meaningful, or alive?</p><div class="bar"><i style="width:38%"></i></div><a href="#/research">Read notes ↗</a></article><article class="library-card"><span class="tag">BACKLOG</span><h3>Maloura Pantry</h3><p>A possible shared shelf for the makers and growers we already know.</p><div class="bar"><i style="width:12%"></i></div><a href="#/ideas">See the idea ↗</a></article></div>`); }
function render() { const route = location.hash.replace('#/', '') || ''; if (route === 'services') servicesPage(); else if (route === 'request') requestPage(); else if (route === 'orders') ordersPage(); else if (route === 'admin') adminPage(); else if (route === 'ideas' || route === 'research') libraryPage(route); else if (route === 'projects') projectsPage(); else home(); }
window.addEventListener('hashchange', render); render();